apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: web
        image: ghcr.io/joshiehsu/argocd-lab-web:3be3ae428bcfbd576c4747adadcfd4254a1ffc9b
        ports:
        - containerPort: 80
