{{- range .Values.trafficSplit.routes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-{{ .version }}   # 讓 Deployment 名稱帶有版本區分（例如 guestbook-ui-v1）
  namespace: default
spec:
  replicas: 2     # 每個版本要跑幾個 Pod
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: guestbook-ui
      version: {{ .version }}       # 關鍵：選擇器對應版本
  template:
    metadata:
      labels:
        app: guestbook-ui
        version: {{ .version }}     # 關鍵：這就是貼給 Pod 看的身分標籤（v1 或 v2）！
    spec:
      containers:
        - name: web
          image: "{{ $.Values.image.repository }}:{{ .imageTag }}"  # 對應不同版本的 Image Tag
          ports:
            - containerPort: 80
{{- end }}
