apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-ui # 告訴 Ingress 把流量轉給剛剛建的 Service
            port:
              number: {{ .Values.service.port }} 
